enable_cnn: true
cnn_int8: false
cnn_fp16: true
cnn_use_tensorrt: true
cnn_type: "hitnet"
onnx_path: "/root/swarm_ws/src/configs-drone-swarm/drones/stereo_depth_est_models/model_float16_quant_opt.onnx"
trt_engine_path: "/root/swarm_ws/src/configs-drone-swarm/drones/stereo_depth_est_models/model_float16_quant_opt_onnx_test.trt"
cnn_input_rgb : false
enable_texture: false
width: 320
height: 240
pixel_step: 2
image_step: 2
max_z: 3
min_z: 0.3
cam_calib_file_path: "/root/swarm_ws/src/D2SLAM/config/quadcam_drone_0/fisheye_cams.yaml"
fov: 190
fps: 10

image_topic: "/oak_ffc_4p/assemble_image"
image_type: "raw"

photometric_calib_numbers: 4
#TODO: refine this process to make vig calibration more easy to read
photometric_calib_path: "/root/swarm_ws/src/D2SLAM/config/quadcam_drone_0/camera_vig_mask"
# photometric_calib_path: ""
# photometric_calib: "mask.png"
photometric_calib: ""
avg_brightness: 0.7
stereos:
  stereo1_0:
    cam_idx_l: 0
    cam_idx_r: 1
    idx_l: 1
    idx_r: 0
    stereo_config: "/root/swarm_ws/src/D2SLAM/config/quadcam_drone_0/stereo_calib_0_1_240_320.yaml"
  stereo2_1:
    cam_idx_l: 1
    cam_idx_r: 2
    idx_l: 1
    idx_r: 0
    stereo_config: "/root/swarm_ws/src/D2SLAM/config/quadcam_drone_0/stereo_calib_1_2_240_320.yaml"
  stereo3_2:
    cam_idx_l: 2
    cam_idx_r: 3
    idx_l: 1
    idx_r: 0
    stereo_config: "/root/swarm_ws/src/D2SLAM/config/quadcam_drone_0/stereo_calib_2_3_240_320.yaml"
  stereo0_3:
    cam_idx_l: 3
    cam_idx_r: 0
    idx_l: 1
    idx_r: 0
    stereo_config: "/root/swarm_ws/src/D2SLAM/config/quadcam_drone_0/stereo_calib_3_0_240_320.yaml"
camera_configuration: 3